swagger: "2.0"
info:
  title: Latex Compiler
  version: 1.0.0
paths:
  /latex/compile:
    post:
      operationId: compileLatex
      security:
        - api_key: []
      x-google-backend:
        address: https://latex-compiler-393050277209.us-central1.run.app/latex/compile
      responses:
        "200":
          description: A successful response
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
